// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64be || armbe || mips || mips64 || mips64p32 || ppc64 || s390 || s390x || sparc || sparc64

package cpu

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type hotspot_bpfCpuState struct {
	Pid uint32
	_   [4]byte
	Ts  uint64
}

type hotspot_bpfPidStat struct {
	CpuTimeNs uint64
	Comm      [16]int8
	Cgroup    [64]int8
	CpuId     uint32
	Pad       uint32
}

// loadHotspot_bpf returns the embedded CollectionSpec for hotspot_bpf.
func loadHotspot_bpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Hotspot_bpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load hotspot_bpf: %w", err)
	}

	return spec, err
}

// loadHotspot_bpfObjects loads hotspot_bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*hotspot_bpfObjects
//	*hotspot_bpfPrograms
//	*hotspot_bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadHotspot_bpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadHotspot_bpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// hotspot_bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hotspot_bpfSpecs struct {
	hotspot_bpfProgramSpecs
	hotspot_bpfMapSpecs
}

// hotspot_bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hotspot_bpfProgramSpecs struct {
	HandleSchedSwitch *ebpf.ProgramSpec `ebpf:"handle_sched_switch"`
}

// hotspot_bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hotspot_bpfMapSpecs struct {
	CpuContention *ebpf.MapSpec `ebpf:"cpu_contention"`
	CpuState      *ebpf.MapSpec `ebpf:"cpu_state"`
	PidStats      *ebpf.MapSpec `ebpf:"pid_stats"`
}

// hotspot_bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadHotspot_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type hotspot_bpfObjects struct {
	hotspot_bpfPrograms
	hotspot_bpfMaps
}

func (o *hotspot_bpfObjects) Close() error {
	return _Hotspot_bpfClose(
		&o.hotspot_bpfPrograms,
		&o.hotspot_bpfMaps,
	)
}

// hotspot_bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadHotspot_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type hotspot_bpfMaps struct {
	CpuContention *ebpf.Map `ebpf:"cpu_contention"`
	CpuState      *ebpf.Map `ebpf:"cpu_state"`
	PidStats      *ebpf.Map `ebpf:"pid_stats"`
}

func (m *hotspot_bpfMaps) Close() error {
	return _Hotspot_bpfClose(
		m.CpuContention,
		m.CpuState,
		m.PidStats,
	)
}

// hotspot_bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadHotspot_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type hotspot_bpfPrograms struct {
	HandleSchedSwitch *ebpf.Program `ebpf:"handle_sched_switch"`
}

func (p *hotspot_bpfPrograms) Close() error {
	return _Hotspot_bpfClose(
		p.HandleSchedSwitch,
	)
}

func _Hotspot_bpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed hotspot_bpf_bpfeb.o
var _Hotspot_bpfBytes []byte
