// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || loong64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64

package memory

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type memory_bpfFaultStat struct {
	Faults   uint64
	RssPages uint64
	Cgroup   [64]int8
}

// loadMemory_bpf returns the embedded CollectionSpec for memory_bpf.
func loadMemory_bpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Memory_bpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load memory_bpf: %w", err)
	}

	return spec, err
}

// loadMemory_bpfObjects loads memory_bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*memory_bpfObjects
//	*memory_bpfPrograms
//	*memory_bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMemory_bpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMemory_bpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// memory_bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memory_bpfSpecs struct {
	memory_bpfProgramSpecs
	memory_bpfMapSpecs
}

// memory_bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memory_bpfProgramSpecs struct {
	HandleMmFaultKprobe *ebpf.ProgramSpec `ebpf:"handle_mm_fault_kprobe"`
}

// memory_bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type memory_bpfMapSpecs struct {
	PageFaults *ebpf.MapSpec `ebpf:"page_faults"`
}

// memory_bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMemory_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type memory_bpfObjects struct {
	memory_bpfPrograms
	memory_bpfMaps
}

func (o *memory_bpfObjects) Close() error {
	return _Memory_bpfClose(
		&o.memory_bpfPrograms,
		&o.memory_bpfMaps,
	)
}

// memory_bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMemory_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type memory_bpfMaps struct {
	PageFaults *ebpf.Map `ebpf:"page_faults"`
}

func (m *memory_bpfMaps) Close() error {
	return _Memory_bpfClose(
		m.PageFaults,
	)
}

// memory_bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMemory_bpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type memory_bpfPrograms struct {
	HandleMmFaultKprobe *ebpf.Program `ebpf:"handle_mm_fault_kprobe"`
}

func (p *memory_bpfPrograms) Close() error {
	return _Memory_bpfClose(
		p.HandleMmFaultKprobe,
	)
}

func _Memory_bpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed memory_bpf_bpfel.o
var _Memory_bpfBytes []byte
